### ISSUE TITLE
Internal Image Size doesn't grow with circle

### ISSUE THREAD

**Issue by eladkatz** [markushi/android-circlebutton#5]
When I put in the button as follows:
        <at.markushi.ui.CircleButton
            android:layout_width="360dip"
            android:layout_height="360dip"
            android:src="@drawable/ic_question_mark"
            app:cb_color="#99CC00"
            app:cb_pressed_ring_width="8dip"
            android:layout_gravity="center"
            />

The image in the center remains the same size as it was before making it bigger

**Comment by enginebai** [comment]
I'm encountering the same issue. When the size of `CircleButton` is bigger than the icon image, the icon will not scale up the the size of the button.

**Comment by phellmayr1** [comment]
The problem exists also, if the image is to big to fit into the button. Then the image overlaps the button and does not get scaled down.

**Comment by AzureusSme** [comment]
It only works with prescaled images, in hdpi and etc. so its limited to that.
